import mongoose from "mongoose";
import dotenv from "dotenv";
dotenv.config();

import { Products } from "./Models/Product.js";

export const sampleProducts = [
  // --- LAPTOPS ---
  {
    title: "Apple MacBook Pro 16\" M3 Max",
    slug: "apple-macbook-pro-16-m3-max",
    brand: "Apple",
    category: "laptop",
    price: 249900,
    originalPrice: 269900,
    discount: 7,
    qty: 15,
    imgSrc: "/images/laptop.webp",
    images: [
      "/images/laptop.webp",
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "The 16-inch MacBook Pro with M3 Max charges through demanding workflows with up to 16-core CPU, up to 40-core GPU, and up to 128GB unified memory. Liquid Retina XDR display provides 1600 nits peak brightness and industry-leading battery life up to 22 hours.",
    shortDescription: "Flagship Apple silicon laptop with M3 Max, Liquid Retina XDR display and 22-hour battery life.",
    specifications: {
      processor: "Apple M3 Max 16-core",
      ram: "36GB Unified Memory",
      storage: "1TB Ultra-Fast SSD",
      display: "16.2-inch Liquid Retina XDR (3456x2234)",
      battery: "Up to 22 Hours",
      weight: "2.16 kg",
      operatingSystem: "macOS Sonoma",
    },
    rating: 4.9,
    reviewCount: 48,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Apple Care Warranty",
    returnPolicy: "7 Days Replacement Guarantee",
  },
  {
    title: "Dell XPS 15 OLED InfinityEdge",
    slug: "dell-xps-15-oled-infinityedge",
    brand: "Dell",
    category: "laptop",
    price: 184990,
    originalPrice: 199990,
    discount: 8,
    qty: 12,
    imgSrc: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80",
      "/images/laptop.webp",
    ],
    description:
      "Precision-crafted with CNC aluminum and carbon fiber, the Dell XPS 15 features a vibrant 3.5K OLED touch display, 13th Gen Intel Core i7 processor, and NVIDIA GeForce RTX 4060 graphics for power-packed creative production.",
    shortDescription: "Premium Windows laptop with 3.5K OLED touch display and NVIDIA RTX 4060 GPU.",
    specifications: {
      processor: "Intel Core i7-13700H 14-core",
      ram: "32GB DDR5 4800MHz",
      storage: "1TB PCIe NVMe SSD",
      display: "15.6-inch 3.5K OLED Touch (3456x2160)",
      gpu: "NVIDIA GeForce RTX 4060 8GB GDDR6",
      operatingSystem: "Windows 11 Pro",
    },
    rating: 4.7,
    reviewCount: 31,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Dell Premium Support",
    returnPolicy: "7 Days Easy Return",
  },
  {
    title: "Lenovo ThinkPad X1 Carbon Gen 11",
    slug: "lenovo-thinkpad-x1-carbon-gen-11",
    brand: "Lenovo",
    category: "laptop",
    price: 154999,
    originalPrice: 174999,
    discount: 11,
    qty: 18,
    imgSrc: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
      "/images/laptop.webp",
    ],
    description:
      "Ultralight business powerhouse weighing just 1.12kg. Built with military-grade carbon fiber chassis, legendary ThinkPad keyboard, Intel Core i7 vPro, and robust biometric privacy shutters.",
    shortDescription: "Ultralight carbon-fiber business laptop engineered for supreme durability and typing comfort.",
    specifications: {
      processor: "Intel Core i7-1365U vPro",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      display: "14-inch 2.8K OLED (2880x1800)",
      weight: "1.12 kg",
      operatingSystem: "Windows 11 Pro",
    },
    rating: 4.8,
    reviewCount: 22,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    freeShipping: true,
    warranty: "3 Years Lenovo Onsite Warranty",
    returnPolicy: "7 Days Return Policy",
  },
  {
    title: "ASUS ROG Zephyrus G16 Gaming Laptop",
    slug: "asus-rog-zephyrus-g16-gaming",
    brand: "ASUS",
    category: "laptop",
    price: 189990,
    originalPrice: 209990,
    discount: 10,
    qty: 8,
    imgSrc: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Sleek CNC aluminum gaming beast equipped with Intel Core Ultra 9, NVIDIA GeForce RTX 4070, and breathtaking 2.5K 240Hz ROG Nebula OLED display with 0.2ms response time.",
    shortDescription: "Ultra-slim gaming laptop with OLED 240Hz display, Core Ultra 9, and RTX 4070 graphics.",
    specifications: {
      processor: "Intel Core Ultra 9 185H",
      ram: "32GB LPDDR5X",
      storage: "1TB PCIe 4.0 SSD",
      display: "16-inch 2.5K OLED 240Hz (2560x1600)",
      gpu: "NVIDIA GeForce RTX 4070 8GB",
      operatingSystem: "Windows 11 Home",
    },
    rating: 4.9,
    reviewCount: 19,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Global Warranty",
    returnPolicy: "7 Days Return Policy",
  },

  // --- SMARTPHONES ---
  {
    title: "Apple iPhone 15 Pro Max 256GB",
    slug: "apple-iphone-15-pro-max-256gb",
    brand: "Apple",
    category: "mobile",
    price: 154900,
    originalPrice: 159900,
    discount: 3,
    qty: 25,
    imgSrc: "/images/mobile.webp",
    images: [
      "/images/mobile.webp",
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Forged in aerospace-grade titanium, iPhone 15 Pro Max features the groundbreaking A17 Pro chip, customizable Action button, 48MP main camera with 5x optical zoom telephoto lens, and USB-C connectivity with USB 3 speeds.",
    shortDescription: "Titanium design, A17 Pro chip, 5x telephoto camera and Super Retina XDR ProMotion display.",
    specifications: {
      processor: "A17 Pro 6-core chip",
      ram: "8GB",
      storage: "256GB NVMe",
      display: "6.7-inch Super Retina XDR OLED 120Hz",
      camera: "48MP Main + 12MP Ultra-Wide + 12MP 5x Telephoto",
      battery: "4422 mAh with MagSafe 15W",
      operatingSystem: "iOS 17",
    },
    rating: 4.9,
    reviewCount: 65,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Official Apple Warranty",
    returnPolicy: "7 Days Replacement",
  },
  {
    title: "Samsung Galaxy S24 Ultra AI Smartphone",
    slug: "samsung-galaxy-s24-ultra-ai",
    brand: "Samsung",
    category: "mobile",
    price: 129999,
    originalPrice: 139999,
    discount: 7,
    qty: 20,
    imgSrc: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80",
      "/images/mobile.webp",
    ],
    description:
      "Meet Galaxy S24 Ultra with Galaxy AI built-in. Features a titanium frame, 200MP camera with Quad Tele system, integrated S Pen stylus, and the Snapdragon 8 Gen 3 for Galaxy with ray tracing capability.",
    shortDescription: "Titanium flagship with 200MP pro camera, integrated S-Pen and revolutionary Galaxy AI.",
    specifications: {
      processor: "Snapdragon 8 Gen 3 for Galaxy",
      ram: "12GB LPDDR5X",
      storage: "256GB UFS 4.0",
      display: "6.8-inch Dynamic AMOLED 2X 120Hz (2600 nits)",
      camera: "200MP + 50MP + 12MP + 10MP",
      battery: "5000 mAh with 45W Fast Charging",
      operatingSystem: "One UI 6.1 (Android 14)",
    },
    rating: 4.8,
    reviewCount: 52,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Samsung India Warranty",
    returnPolicy: "7 Days Replacement",
  },
  {
    title: "Google Pixel 8 Pro with Gemini Nano",
    slug: "google-pixel-8-pro-gemini-nano",
    brand: "Google",
    category: "mobile",
    price: 98999,
    originalPrice: 106999,
    discount: 7,
    qty: 14,
    imgSrc: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Powered by Google Tensor G3 with custom AI capabilities like Best Take, Magic Audio Eraser, and Pro camera controls. Includes 7 years of OS updates and a super bright Super Actua display.",
    shortDescription: "Pure Android flagship with Google Tensor G3, legendary computational photography and 7 years of updates.",
    specifications: {
      processor: "Google Tensor G3 with Titan M2",
      ram: "12GB LPDDR5X",
      storage: "128GB UFS 3.1",
      display: "6.7-inch Super Actua LTPO OLED 120Hz",
      camera: "50MP Main + 48MP Ultra-wide + 48MP 5x Telephoto",
      battery: "5050 mAh with 30W Fast Charging",
      operatingSystem: "Android 14 (7 Years Support)",
    },
    rating: 4.7,
    reviewCount: 29,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Manufacturer Warranty",
    returnPolicy: "7 Days Return Policy",
  },
  {
    title: "OnePlus 12 5G Hasselblad Camera",
    slug: "oneplus-12-5g-hasselblad",
    brand: "OnePlus",
    category: "mobile",
    price: 64999,
    originalPrice: 69999,
    discount: 7,
    qty: 22,
    imgSrc: "https://images.unsplash.com/photo-1511707171634-5f897ff02543?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02543?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Featuring Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera System with 3x periscope telephoto lens, 100W SUPERVOOC charging, and industry-leading 4500 nit 2K ProXDR display with Aqua Touch.",
    shortDescription: "High-value flagship with Snapdragon 8 Gen 3, 100W ultra-fast charging, and Hasselblad tuned cameras.",
    specifications: {
      processor: "Qualcomm Snapdragon 8 Gen 3",
      ram: "16GB LPDDR5X",
      storage: "512GB UFS 4.0",
      display: "6.82-inch 2K 120Hz ProXDR AMOLED (4500 nits)",
      camera: "50MP Sony LYT-808 + 64MP 3x Periscope + 48MP UW",
      battery: "5400 mAh with 100W SUPERVOOC",
      operatingSystem: "OxygenOS 14 (Android 14)",
    },
    rating: 4.8,
    reviewCount: 41,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Official OnePlus Warranty",
    returnPolicy: "7 Days Return Policy",
  },

  // --- CAMERAS ---
  {
    title: "Sony Alpha 7 IV Full-Frame Mirrorless",
    slug: "sony-alpha-7-iv-full-frame",
    brand: "Sony",
    category: "camera",
    price: 219990,
    originalPrice: 242990,
    discount: 9,
    qty: 9,
    imgSrc: "/images/camera.webp",
    images: [
      "/images/camera.webp",
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "The benchmark hybrid camera for creators. Features a 33MP Exmor R CMOS sensor, 4K 60p 10-bit 4:2:2 video, S-Cinetone color profile, 759 phase-detection AF points with Real-time Eye AF for humans, animals, and birds.",
    shortDescription: "Industry-standard hybrid full-frame camera with 33MP sensor and 4K 60p video recording.",
    specifications: {
      sensor: "33.0MP Full-Frame Exmor R BSI CMOS",
      processor: "BIONZ XR Image Processor",
      video: "4K 60p 10-Bit 4:2:2, S-Cinetone",
      autofocus: "759-Point Phase Detection with Real-time AF",
      stabilization: "5-Axis SteadyShot Sensor-Shift (5.5 stops)",
      isoRange: "100-51200 (Expandable to 50-204800)",
    },
    rating: 4.9,
    reviewCount: 38,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "2 Years Official Sony India Warranty",
    returnPolicy: "7 Days Replacement",
  },
  {
    title: "Canon EOS R6 Mark II Mirrorless Camera",
    slug: "canon-eos-r6-mark-ii",
    brand: "Canon",
    category: "camera",
    price: 204995,
    originalPrice: 224995,
    discount: 9,
    qty: 7,
    imgSrc: "https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=800&q=80",
      "/images/camera.webp",
    ],
    description:
      "Versatile full-frame creator powerhouse delivering up to 40 fps continuous shooting with electronic shutter, 6K oversampled uncropped 4K 60p video, and Dual Pixel CMOS AF II with Deep Learning technology.",
    shortDescription: "Speed-focused mirrorless camera offering 40fps burst shooting and 6K oversampled 4K 60p video.",
    specifications: {
      sensor: "24.2MP Full-Frame CMOS Sensor",
      processor: "DIGIC X Image Processor",
      burstRate: "Up to 40 fps Electronic / 12 fps Mechanical",
      video: "6K Oversampled 4K 60p 10-Bit Internal",
      stabilization: "In-Body Image Stabilizer up to 8.0 Stops",
    },
    rating: 4.8,
    reviewCount: 25,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "2 Years Canon India Warranty",
    returnPolicy: "7 Days Return Policy",
  },
  {
    title: "Fujifilm X-T5 Mirrorless Camera Body",
    slug: "fujifilm-x-t5-mirrorless",
    brand: "Fujifilm",
    category: "camera",
    price: 169999,
    originalPrice: 179999,
    discount: 6,
    qty: 11,
    imgSrc: "https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Classic tactile controls packed with a modern 40.2MP X-Trans CMOS 5 HR sensor, 19 legendary Film Simulation modes, 7 stops of in-body image stabilization, and 6.2K 30p internal recording.",
    shortDescription: "Vintage aesthetics meet high resolution with 40MP sensor and iconic Fujifilm film simulations.",
    specifications: {
      sensor: "40.2MP APS-C X-Trans CMOS 5 HR BSI",
      shutterSpeed: "1/180,000 sec electronic shutter",
      video: "6.2K 30p, 4K 60p 10-bit internal",
      stabilization: "5-Axis 7.0-stop In-Body Image Stabilization",
    },
    rating: 4.9,
    reviewCount: 30,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: false,
    isActive: true,
    freeShipping: true,
    warranty: "2 Years Fujifilm Warranty",
    returnPolicy: "7 Days Return Policy",
  },

  // --- AUDIO & ACCESSORIES ---
  {
    title: "Sony WH-1000XM5 Wireless ANC Headphones",
    slug: "sony-wh-1000xm5-wireless-anc",
    brand: "Sony",
    category: "accessories",
    price: 26990,
    originalPrice: 34990,
    discount: 23,
    qty: 30,
    imgSrc: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Industry-leading noise cancellation powered by two processors and 8 microphones. Enjoy precision-engineered high-resolution audio, crystal clear hands-free calling with 4 beamforming mics, and 30-hour battery life with quick charging.",
    shortDescription: "Flagship wireless noise cancelling over-ear headphones with 30-hour battery life and LDAC Hi-Res audio.",
    specifications: {
      driver: "30mm precision engineered carbon fiber",
      batteryLife: "Up to 30 hours with ANC on (40 hrs off)",
      connectivity: "Bluetooth 5.2, Multipoint, LDAC, 3.5mm",
      weight: "250g",
    },
    rating: 4.8,
    reviewCount: 78,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Sony Warranty",
    returnPolicy: "7 Days Replacement",
  },
  {
    title: "Apple AirPods Pro (2nd Gen) with USB-C",
    slug: "apple-airpods-pro-2nd-gen-usb-c",
    brand: "Apple",
    category: "accessories",
    price: 22990,
    originalPrice: 24900,
    discount: 8,
    qty: 40,
    imgSrc: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Powered by Apple H2 chip, AirPods Pro features up to 2x more Active Noise Cancellation, Adaptive Audio, Transparency mode, and Personalized Spatial Audio with dynamic head tracking. MagSafe Case includes USB-C and speaker.",
    shortDescription: "Pro-tier earbuds with H2 chip, 2x active noise cancellation and MagSafe USB-C case.",
    specifications: {
      chip: "Apple H2 headphone chip + U1 case chip",
      battery: "Up to 6 hours listening (30 hours with case)",
      durability: "IP54 dust, sweat, and water resistant",
    },
    rating: 4.9,
    reviewCount: 95,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Official Apple Warranty",
    returnPolicy: "7 Days Return Policy",
  },
  {
    title: "Apple Watch Ultra 2 GPS + Cellular",
    slug: "apple-watch-ultra-2-gps-cellular",
    brand: "Apple",
    category: "accessories",
    price: 89900,
    originalPrice: 89900,
    discount: 0,
    qty: 15,
    imgSrc: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "The most rugged and capable Apple Watch. Features a lightweight 49mm titanium case, ultra-bright 3000-nit display, S9 SiP with Double Tap gesture, precision dual-frequency GPS, and up to 36 hours of normal battery life.",
    shortDescription: "49mm titanium rugged smartwatch built for athletes, adventurers, and deep divers.",
    specifications: {
      caseSize: "49mm Aerospace Titanium Case",
      display: "Always-On Retina OLED (3000 nits)",
      waterResistance: "100m water resistant / 40m recreational dive",
      battery: "Up to 36 hours (72 hrs in Low Power Mode)",
    },
    rating: 4.9,
    reviewCount: 34,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Apple Warranty",
    returnPolicy: "7 Days Return Policy",
  },
  {
    title: "Keychron Q1 Pro Wireless Custom Mechanical Keyboard",
    slug: "keychron-q1-pro-wireless",
    brand: "Keychron",
    category: "accessories",
    price: 17999,
    originalPrice: 19999,
    discount: 10,
    qty: 16,
    imgSrc: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
    ],
    description:
      "Full CNC aluminum body, 75% layout custom mechanical keyboard with QMK/VIA programmable knobs, hot-swappable switches, double-gasket mount design, and Bluetooth 5.1 wireless connectivity.",
    shortDescription: "Custom 75% mechanical keyboard with CNC aluminum frame, hot-swappable switches and wireless connectivity.",
    specifications: {
      layout: "75% ANSI Layout (81 Keys + Knob)",
      material: "Full CNC Machined Aluminum Body",
      switches: "Keychron K Pro Red / Brown Pre-lubed",
      connectivity: "Bluetooth 5.1 & Type-C Wired",
    },
    rating: 4.8,
    reviewCount: 16,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    freeShipping: true,
    warranty: "1 Year Warranty",
    returnPolicy: "7 Days Return Policy",
  },
];

async function seed() {
  try {
    const mongoUri =
      process.env.MONGO_URI ||
      "mongodb+srv://shivamsinghmahewa7698_db_user:aKCoWAa4mJMYF3hG@cluster0.chl73tb.mongodb.net/";

    await mongoose.connect(mongoUri, { dbName: "MERN_E_Commerce" });
    console.log("Connected to MongoDB for seeding...");

    // Clear existing products
    await Products.deleteMany({});
    console.log("Cleared old products...");

    // Insert rich product catalog
    const inserted = await Products.insertMany(sampleProducts);
    console.log(`Successfully seeded ${inserted.length} premium products into database!`);

    process.exit(0);
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
}

if (process.argv[1] && process.argv[1].includes("seedProducts.js")) {
  seed();
}
